{
    "name": "Kannatusseura",
    "summary": "Manage supporting organizations (FIN: kannatusseura) for partners",
    "author": "Futural",
    "website": "https://github.com/tawasta/partner",
    "category": "CRM",
    "version": "17.0.1.0.0",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": ["contacts", "portal", "website"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/kannatusseura_views.xml",
        "views/kannatusseura_cat.xml",
        "views/portal_view.xml",
        "views/res_partner_views.xml",
    ],
}
